version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx4G
    steps:
      - filters:
          branches:
            only:
              - develop 
      - checkout
      - run: echo "Working on some stuff..."
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Initial build
          command: ./gradlew clean assembleDebug --no-daemon --stacktrace
      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apks/
      - deploy:
          name: "Deploy to Fabric 🎉🎉"
          command: |
            echo "Branch: ${CIRCLE_BRANCH} , PR: ${CIRCLE_PULL_REQUEST}"
            ./gradlew crashlyticsUploadDistributionDebug --stacktrace --debug --no-daemon
